config/routes.rb
Unrefined::Application.routes.draw do
  resources :postings


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users

  match '/testing', :to => "home#vocal"
  match '/about', :to => "home#about"
  match '/blog', :to => "home#blog"
  match '/contact', :to => "home#contact"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/posting.rb
class Posting < ActiveRecord::Base
  belongs_to :user
  attr_accessible :body, :title, :user_id
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me

  has_many :postings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def blog
    @blogs = Posting.all.sort_by{ |i| i.created_at }.reverse
  end

  def about
  end

  def contact
  end

  def vocal
    system('say -v Zarvox "Sequence aborted."')
    redirect_to root_path
  end

end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController
  # GET /postings
  # GET /postings.json
  def index
    authorize! :index, current_user, :message => 'Not authorized as an administrator.'
    @postings = Posting.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @postings }
    end
  end

  # GET /postings/1
  # GET /postings/1.json
  def show
    @posting = Posting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @posting }
    end
  end

  # GET /postings/new
  # GET /postings/new.json
  def new
    @posting = Posting.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @posting }
    end
  end

  # GET /postings/1/edit
  def edit
    @posting = Posting.find(params[:id])
  end

  # POST /postings
  # POST /postings.json
  def create
    @posting = Posting.new(params[:posting])

    respond_to do |format|
      if @posting.save
        format.html { redirect_to @posting, notice: 'Posting was successfully created.' }
        format.json { render json: @posting, status: :created, location: @posting }
      else
        format.html { render action: "new" }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /postings/1
  # PUT /postings/1.json
  def update
    @posting = Posting.find(params[:id])

    respond_to do |format|
      if @posting.update_attributes(params[:posting])
        format.html { redirect_to @posting, notice: 'Posting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @posting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /postings/1
  # DELETE /postings/1.json
  def destroy
    @posting = Posting.find(params[:id])
    @posting.destroy

    respond_to do |format|
      format.html { redirect_to postings_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/postings_helper.rb
module PostingsHelper
end

app/views/home/about.html.haml
%h1 About This Site
%p
  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam sit amet quam at enim semper viverra. Phasellus tortor nulla, pulvinar vitae bibendum at, rhoncus non tortor. Nunc quis massa dui. Aliquam et libero ipsum. Nullam commodo tristique eros, in laoreet justo interdum vel. Ut purus ligula, auctor eget pellentesque vitae, blandit vel dolor. Vestibulum id augue ac augue suscipit posuere nec a lacus. In vehicula magna ut erat fringilla egestas. Ut tincidunt enim eget tellus facilisis ultricies. In hac habitasse platea dictumst. Aliquam commodo scelerisque dolor, in convallis urna eleifend iaculis. Vivamus et sapien ultrices elit convallis ultricies. Donec sodales volutpat sapien non euismod. In hac habitasse platea dictumst.

  Mauris lacus libero, gravida non cursus ut, facilisis at dui. Quisque risus ligula, blandit sodales adipiscing quis, placerat sit amet nulla. Cras in ligula non nisi vulputate condimentum. Mauris tempus pharetra odio, sit amet dapibus nisl lacinia non. Donec rutrum metus vel mauris pellentesque id aliquet nulla elementum. Fusce adipiscing, leo suscipit aliquet semper, lectus tortor dictum arcu, aliquam ornare erat orci a enim. Mauris mattis rhoncus sem eu pharetra. Integer venenatis, dui vel semper consequat, metus nisi pretium augue, fermentum tincidunt nisl eros sed lacus. Quisque non erat purus, quis tempor magna. Ut ullamcorper semper laoreet. Nunc blandit tempor metus, et tincidunt odio bibendum ac. Cras hendrerit elit vel tortor ultrices et adipiscing augue venenatis. Aliquam erat volutpat. Nullam a nulla tortor, nec euismod risus. Curabitur nec est nunc, sit amet pharetra leo.

  Ut augue augue, auctor vel sollicitudin scelerisque, tristique vitae est. Sed in massa mi, in aliquet metus. Sed nec urna in enim tincidunt vulputate. Donec ultrices mi quis lorem porttitor vehicula. Morbi ac accumsan purus. Nunc eget purus nibh, eu placerat tellus. Integer varius augue a sapien pretium volutpat. Vivamus tincidunt iaculis eleifend. Donec neque dolor, rhoncus vitae consequat ac, volutpat vitae quam. Integer eget dui ut tortor porttitor fringilla ut id sapien. Fusce convallis lorem quis nisi fringilla non laoreet sem aliquet. Nulla facilisi.

  Nullam quis leo ut augue luctus ultrices ut vel metus. Praesent lobortis rutrum malesuada. Vivamus gravida nibh tincidunt ante lacinia elementum. Nunc tortor velit, egestas a ultrices at, varius quis mauris. Proin tristique hendrerit orci quis blandit. Duis commodo consectetur felis sit amet vulputate. Cras ullamcorper, nisi nec tincidunt ultricies, quam nibh sodales neque, eget sollicitudin nulla leo sit amet lacus. Ut ullamcorper eros quis augue mattis ac semper dui pulvinar. Nam et ultricies ante. Quisque sem nulla, posuere nec egestas sit amet, rhoncus eu enim. Aliquam et nisi sed urna laoreet lacinia in a dolor. Suspendisse iaculis congue sapien, vel dignissim purus suscipit nec. Integer tempor ultricies consequat. Etiam eget consectetur velit. Vestibulum quam libero, porttitor dictum sollicitudin ac, ultricies non sapien. Curabitur lacinia egestas dignissim.

  Donec commodo luctus nibh, vel consectetur ipsum adipiscing id. Ut semper purus ut nisl euismod commodo. Fusce eget sapien lacus. Vivamus eu cursus felis. Aenean turpis libero, congue sit amet dignissim et, euismod at sem. Curabitur faucibus pulvinar lacus nec vestibulum. Integer vel tellus enim. Nulla sed bibendum sapien. In a tempus arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Aenean sed tortor vitae diam laoreet ullamcorper nec posuere libero. Nullam ac enim id massa placerat vestibulum. Sed fermentum egestas nibh gravida viverra.

app/views/home/blog.html.haml
%h1 My Crazy Life
%br/
.span12
  - @blogs.each do |blog|
    .well.span3
      %h5=blog.title
      %br/
      %br/
      %p
        =blog.body
      %br/
      %br/
      .timestamp
        = "#{blog.user.name} authored #{distance_of_time_in_words(blog.created_at, Time.now)} ago"
      %br/

app/views/home/contact.html.haml
%h1 Contact Us
%p
  Go ahead and contact us if you can.

app/views/layouts/_messages.html.haml
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name == :notice ? "success" : "error"}"}
      %a.close{"data-dismiss" => "alert"} ×
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_navigation.html.haml
= link_to "Rails-Devise-AngularJS-haml", root_path, :class => 'brand'
.pull-right
  %ul.nav
    - if user_signed_in?
      %li
        = link_to 'Logout', destroy_user_session_path, :method=>'delete'
    - else
      %li
        = link_to 'Login', new_user_session_path
    - if user_signed_in?
      %li
        = link_to 'Edit account', edit_user_registration_path
      - if current_user.has_role? :admin
        %li
          = link_to 'New Blog', postings_path
        %li
          = link_to 'Admin', users_path
    - else
      %li
        = link_to 'Sign up', new_user_registration_path

app/views/layouts/application.html.haml
!!!
%html{:lang => "en", "ng-app" => "tutorialApp"}
  %head
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}
      %title= content_for?(:title) ? yield(:title) : "AngularJS"
      %meta{:content => content_for?(:description) ? yield(:description) : "AngularJS", :name => "description"}
        = stylesheet_link_tag "application", :media => "all"
        = javascript_include_tag "application"
        = csrf_meta_tags
        = yield(:head)
  %body{:class => "#{controller_name} #{action_name}"}
    .navbar.navbar-fixed-top
      %nav.navbar-inner
        .container
          = render 'layouts/navigation'
    #main{:role => "main"}
      .container
        .row
          .span12
            = render 'layouts/messages'
            = yield
        %footer
      / ! end of .container
    / ! end of #main

app/views/postings/_form.html.haml
= simple_form_for(@posting) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, :input_html => { class: 'span6' }
    = f.input :body, :input_html => { class: 'span6', rows: 7 }
    = f.input :user_id, :as => :hidden, :input_html => { value: current_user.id }

    = f.button :submit, "Publish"

app/views/postings/edit.html.haml
%h1 Editing posting

= render 'form'

= link_to 'Show', @posting
\|
= link_to 'Back', postings_path, class: 'btn btn-primary'

app/views/postings/index.html.haml
%h1 Listing postings

%table.table.table-striped
  %tr
    %th Title
    %th Body
    %th User
    %th
    %th
    %th

  - @postings.each do |posting|
    %tr
      %td= posting.title
      %td= posting.body
      %td= posting.user.name
      %td= link_to 'Show', posting, class: 'btn btn-primary'
      %td= link_to 'Edit', edit_posting_path(posting), class: 'btn btn-info'
      %td= link_to 'Destroy', posting, class: 'btn btn-danger', :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Posting', new_posting_path, class: 'btn'

app/views/postings/new.html.haml
%h1 New posting

= render 'form'

= link_to 'Back', postings_path, class: 'btn btn-primary'

app/views/postings/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @posting.title
%p
  %b Body:
  = @posting.body
%p
  %b User:
  = @posting.user.name

= link_to 'Edit', edit_posting_path(@posting)
\|
= link_to 'Back', postings_path

app/views/users/_user.html.haml
.modal{:id => "role-options-#{user.id}", :style => "display: none;"}
  = simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f|
    .modal-header
      %a.close{"data-dismiss" => "modal"} ×
      %h3 Change Role
    .modal-body
      = f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline', checked: user.role_ids.first
    .modal-footer
      = f.submit "Change Role", :class => "btn"
      %a.btn{"data-dismiss" => "modal", :href => "#"} Close

app/views/users/index.html.haml
%h3 Users
.span8
  %table.table.table-condensed
    %thead
      %tr
        %th Username
        %th Email
        %th Registered
        %th Role
        %th
        %th
    %tbody
      - @users.each do |user|
        %tr
          %td= link_to user.name, user
          %td= user.email
          %td= user.created_at.to_date
          %td= user.roles.first.name.titleize unless user.roles.first.nil?
          %td
            %a.btn.btn-mini{"data-toggle" => "modal", :href => "#role-options-#{user.id}", :type => "button"} Change role
            = render user
          %td= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user

app/views/users/show.html.haml
%h3 User
%p
  User: #{@user.name}
%p
  Email: #{@user.email if @user.email}